# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  TRAINED_MODEL_DIR: model
  BASE_MODEL_DIR: base_model
  BASE_MODEL_NAME: base_model.h5
  UPDATED_BASE_MODEL_NAME: updated_base_model.h5
  CHECKPOINT_DIR: checkpoints
  BASE_LOG_DIR: base_model_dir
  TENSORBOARD_ROOT_LOG_DIR: tensorboard_log_dir
  CALLBACKS_DIR: callbacks

source_download_dirs:
  train: /home/ravikumar/Desktop/pythonista/my_trainings/data/dogcat/train
  test: /home/ravikumar/Desktop/pythonista/my_trainings/data/dogcat/test1

local_data_dirs:
  data: data
  train: data/train
  test: data/test
  train_dog: data/train/dog
  train_cat: data/train/cat
  test_dog: data/test/dog
  test_cat: data/test/cat
  
